export const ActionTypes = {
    'CREATE_POST': 'CREATE_POST',
    'GET_ALL_POSTS': 'GET_ALL_POSTS',
    'POST_FAIL': 'POST_FAIL',
    'DELETE_POST': 'DELETE_POST',
    'DELETE_FAIL': 'DELETE_FAIL',
    'UPDATE_POST': 'UPDATE_POST'
}