export const ActionTypes = {
    'GET_PROFILE': 'GET_PROFILE',
    'PROFILE_ERROR': 'PROFILE_ERROR',
    'ADD_EXPERIENCE': 'ADD_EXPERIENCE',
    'DELETE_EXPERIENCE': 'DELETE_EXPERIENCE',
    'PROFILE_PUBLIC': 'PROFILE_PUBLIC',
    'PROFILE_PUBLIC_ERROR': 'PROFILE_PUBLIC_ERROR'
}